void reset_to_98(int *n);
void swap_int(int *n, int *m);
int _strlen(char *c);
void _puts(char *str);
int _putchar(char);
void print_rev(char *s);
void rev_string(char *s);
void puts2(char *s);
void puts_half(char *s);
void print_array(int *arr, int n);
char *_strcpy(char *dest, char *src);
int _atoi(char *c);
int stoi_max(char *c, int max, int sign);
